version: "3"
services:
  db:
    image: postgres:15
    volumes:
      - ./db:/var/lib/postgresql/data/
    restart: "on-failure"
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
  musicshowwins:
    build:
      context: ./musicshowwins
      dockerfile: Dockerfile
    restart: "always"
    command: sh -c "python3 manage.py makemigrations &&
      python3 manage.py migrate &&
      python3 manage.py collectstatic --no-input &&
      gunicorn musicshowwins.wsgi:application --bind 0.0.0.0:8002"
    volumes:
      - ./musicshowwins:/usr/src/app
      - staticfiles:/usr/src/app/staticfiles
    expose:
      - 8002
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
  nginx:
    build:
      context: ./nginx
    restart: "always"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - staticfiles:/usr/src/app/staticfiles
    ports:
      - ${NGINX_PORT}:80
    depends_on:
      - musicshowwins

volumes:
  staticfiles:
