# Generated by Django 5.2

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("identity_key", models.CharField(editable=False, max_length=200, unique=True)),
            ],
            options={"ordering": ("name",)},
        ),
        migrations.CreateModel(
            name="ImportRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("running", "Running"), ("completed", "Completed"), ("failed", "Failed")], default="running", max_length=20)),
                ("requested_shows", models.JSONField(default=list)),
                ("requested_years", models.JSONField(default=list)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("wins_added", models.PositiveIntegerField(default=0)),
                ("conflicts_found", models.PositiveIntegerField(default=0)),
                ("pages_processed", models.PositiveIntegerField(default=0)),
                ("failure_summary", models.TextField(blank=True)),
            ],
            options={"ordering": ("-started_at",)},
        ),
        migrations.CreateModel(
            name="MusicShow",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("active", models.BooleanField(default=True)),
            ],
            options={"ordering": ("name",)},
        ),
        migrations.CreateModel(
            name="ArtistAlias",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("alias", models.CharField(max_length=200)),
                ("normalized_name", models.CharField(editable=False, max_length=200)),
                ("artist", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="aliases", to="main.artist")),
            ],
            options={"ordering": ("alias",)},
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=300)),
                ("normalized_title", models.CharField(editable=False, max_length=300)),
                ("artist", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="songs", to="main.artist")),
            ],
            options={"ordering": ("title", "artist__name")},
        ),
        migrations.CreateModel(
            name="SourcePage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("year", models.PositiveSmallIntegerField()),
                ("page_title", models.CharField(max_length=255)),
                ("latest_revision", models.CharField(blank=True, max_length=80)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("show", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="source_pages", to="main.musicshow")),
            ],
            options={"ordering": ("-year", "show__name")},
        ),
        migrations.CreateModel(
            name="Win",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("source_type", models.CharField(choices=[("legacy", "Legacy bootstrap"), ("wikipedia", "Wikipedia")], default="legacy", max_length=20)),
                ("source_revision", models.CharField(blank=True, max_length=80, null=True)),
                ("show", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="wins", to="main.musicshow")),
                ("song", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="wins", to="main.song")),
                ("source_page", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="wins", to="main.sourcepage")),
            ],
            options={"ordering": ("-date", "show__name", "song__title")},
        ),
        migrations.CreateModel(
            name="ImportIssue",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("issue_type", models.CharField(choices=[("conflict", "Winner conflict"), ("invalid_source", "Invalid source"), ("missing_win", "Missing historical win"), ("fetch_error", "Fetch error")], max_length=30)),
                ("candidate", models.JSONField(default=dict)),
                ("resolution", models.CharField(choices=[("open", "Open"), ("accepted", "Accepted"), ("rejected", "Rejected")], default="open", max_length=20)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("import_run", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="issues", to="main.importrun")),
                ("source_page", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="issues", to="main.sourcepage")),
            ],
            options={"ordering": ("-created_at",)},
        ),
        migrations.AddConstraint(
            model_name="artistalias",
            constraint=models.UniqueConstraint(fields=("normalized_name",), name="unique_artist_alias_normalized_name"),
        ),
        migrations.AddConstraint(
            model_name="song",
            constraint=models.UniqueConstraint(fields=("artist", "normalized_title"), name="unique_song_artist_normalized_title"),
        ),
        migrations.AddConstraint(
            model_name="sourcepage",
            constraint=models.UniqueConstraint(fields=("show", "year"), name="unique_source_page_show_year"),
        ),
        migrations.AddConstraint(
            model_name="win",
            constraint=models.UniqueConstraint(fields=("show", "song", "date"), name="unique_win_show_song_date"),
        ),
        migrations.AddIndex(
            model_name="win",
            index=models.Index(fields=("date",), name="main_win_date_045318_idx"),
        ),
        migrations.AddIndex(
            model_name="win",
            index=models.Index(fields=("show", "date"), name="main_win_show_id_8a27fa_idx"),
        ),
    ]
