# Generated by Django 4.2.3 on 2023-08-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArtistFix",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old", models.CharField(max_length=100)),
                ("new", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="SongFix",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old", models.CharField(max_length=100)),
                ("new", models.CharField(max_length=100)),
            ],
        ),
    ]
