# Generated by Django 4.2.3 on 2023-08-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_artistfix_songfix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artist",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="musicshow",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
