# Generated by Django 4.2.3 on 2023-08-24 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_artist_name_alter_musicshow_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="RemoteAddr",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("remote_addr", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="RequestMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_method", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="RequestPath",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_path", models.CharField(default="/", max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Access",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "http_user_agent",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "query_string",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("time_local", models.DateTimeField(auto_now_add=True)),
                (
                    "remote_addr",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.remoteaddr",
                    ),
                ),
                (
                    "request_method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.requestmethod",
                    ),
                ),
                (
                    "request_path",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.requestpath",
                    ),
                ),
            ],
        ),
    ]
