# Generated by Django 4.2.3 on 2024-01-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_remoteaddr_requestmethod_requestpath_access"),
    ]

    operations = [
        migrations.CreateModel(
            name="URLApprovalStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=255, unique=True)),
                ("approved", models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name="Access",
        ),
        migrations.DeleteModel(
            name="RemoteAddr",
        ),
        migrations.DeleteModel(
            name="RequestMethod",
        ),
        migrations.DeleteModel(
            name="RequestPath",
        ),
    ]
