# Generated by Django 5.2.17 on 2026-09-25 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_winreference_withdrawn'),
    ]

    operations = [
        migrations.AddField(
            model_name='win',
            name='performed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
