# Generated by Django 5.2.17 on 2026-09-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_music_bank_postponed_episode_presence'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='debut',
            field=models.CharField(blank=True, editable=False, max_length=10),
        ),
        migrations.AddField(
            model_name='artist',
            name='debut_solo',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
