# Generated by Django 5.2.17 on 2026-09-30 18:32

import django.db.models.deletion
from django.db import migrations, models


def reparse_sources(apps, schema_editor):
    # Pages are skipped while their revision is unchanged; forget the stored
    # revisions so the next sync parses them again and records episode statuses.
    apps.get_model("main", "SourcePage").objects.update(latest_revision="")


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_artist_debut'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpisodeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('not_aired', 'Not aired'), ('special', 'Special episode, no chart'), ('no_winner', 'No winner announced')], max_length=20)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('source_revision', models.CharField(blank=True, max_length=80)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episode_statuses', to='main.musicshow')),
                ('source_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='episode_statuses', to='main.sourcepage')),
            ],
            options={
                'ordering': ('-date', 'show__name'),
                'constraints': [models.UniqueConstraint(fields=('show', 'date'), name='unique_episode_status_show_date')],
            },
        ),
        migrations.RunPython(reparse_sources, migrations.RunPython.noop),
    ]
